# Generated by Django 4.2.20 on 2025-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_assignedby_task_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_status'], name='tasks_task_task_st_c1502c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'),
        ),
    ]
